server:
  port: 5601

spring:
  application:
    name: fshop-item
  cloud:
    nacos:
      server-addr: 192.168.138.81:8848 # nacos地址
      discovery:
        ip: 10.225.196.74
  datasource:
    url: jdbc:mysql://localhost/catCC?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ftp:
    ip: 47.115.213.55
    port: 21
    username: fshop
    password: sKnGedm4sZN7R67w
    path: /www/wwwroot/fshop
  knife4j:
    enable: true
    openapi:
      title: fshop商品管理接口文档
      email: chenqihui352@163.com
      concat: crc
      version: 1.0.0
      group:
        default:
          group-name: 默认分组
          api-rule: package
          api-rule-resources:
            -com.fshop.item.controller

#输出mysql日志
logging:
  level:
    org:
      mybatis: debug